### PR TITLE
Tool: take shoot of website

### PR DESCRIPTION
**Pull request by lusarz**

### CODE REVIEW

**Comment by jesusprubio** [comment]
Hi, thanks for contributing, you're the first one :smile: :tada: .

Sorry, it was my fault not to add some notes, I've just added them now: https://github.com/jesusprubio/pwr/blob/master/.github/CONTRIBUTING.md#how-to-add-a-tool

So, could you please use the CLI instead? You only would have to:
- npm i --save puppeter-cli
- Add a new entry [here](https://github.com/jesusprubio/pwr/blob/master/tools.json#L29), you can use this one as base, because it also asks for a parameter. We should ask, at least, for the url to snapshoot.

Please ask any questions here: https://t.me/joinchat/AEbIlBbR8ARQoZWZcaMamw

**Comment by lusarz** [comment]
Thank you for friendly welcome and clarification of requirements :) I was not aware that `puppeteer-cli` exists at all. I'll update pull request to meet "This tool only calls the CLIs directly" requirement :)

**Comment by lusarz** [comment]
Okay, I've update pull request. Let me know if questions, params etc should be changed here.

**Comment by jesusprubio** [comment]
Nice, thank you. Only one thing else, please add `puppeter-cli` [here](https://github.com/jesusprubio/pwr/blob/master/package.json#L39) to avoid to break the [workflow](https://travis-ci.org/jesusprubio/pwr/jobs/509342729).

I know it's not comfortable, specially in this app with so much CLIs, but it's nice to avoid not needed ones.

**Review by jesusprubio — APPROVED** [review]

**Comment by lusarz** [comment]
Thank you for approve :) Do you know how to fix `Failed security audit due to moderate vulnerabilities` ?

**Comment by jesusprubio** [comment]
I'm working now and I can't check, but we need to run `npm-audit` to see which dependencies are vulnerable

**Comment by jesusprubio** [comment]
The outdated dependencies are not related with this PR, thank you! :)

**Pull request merged**
